# Generated by Django 5.1.6 on 2025-02-26 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('quest', models.TextField(blank=True, null=True)),
                ('num', models.BigIntegerField(primary_key=True, serialize=False)),
                ('y', models.FloatField(blank=True, null=True)),
                ('n', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.questions')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
    ]
