# Generated by Django 5.1.6 on 2025-02-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={},
        ),
    ]
