# Generated by Django 5.1.6 on 2025-03-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_answers_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
